# Generated by Django 2.1.3 on 2018-11-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('chapter_summary', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_meaning', models.CharField(max_length=100)),
                ('name_translation', models.CharField(max_length=100)),
                ('name_transliterated', models.CharField(max_length=100)),
                ('verses_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('meaning', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=300)),
                ('transliteration', models.CharField(max_length=300)),
                ('verse_number', models.CharField(max_length=100)),
                ('word_meanings', models.CharField(max_length=300)),
            ],
        ),
    ]
