# Generated by Django 2.1.3 on 2018-11-15 02:28

from django.db import migrations, models
import json
from gitarandom.models import Chapter


def insert_chapter(apps, schema_editor):
    with open('gitarandom/static/gitarandom/chapters.json') as data_file:    
        data = json.load(data_file)

    for item in data:
        # Update, map field for item to make it match with Model
        # item['description'] = 'Just kidding'
        Chapter.objects.create(**item)

class Migration(migrations.Migration):

    dependencies = [
        ('gitarandom', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(insert_chapter),
    ]
