# Generated by Django 2.1.3 on 2018-11-15 02:34

from django.db import migrations, models
import json
from gitarandom.models import Verse


def insert_verse(apps, schema_editor):
    with open('gitarandom/static/verses.json') as data_file:    
        data = json.load(data_file)

    for item in data:
        # Update, map field for item to make it match with Model
        # item['description'] = 'Just kidding'
        Verse.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('gitarandom', '0002_auto_20181114_2328'),
    ]

    operations = [
    	migrations.RunPython(insert_verse),
    ]
